In [14]:
# PROCESAMIENTO DIGITAL
# Se importan las librería numpy y las funciones de preprocesamiento
#Editado por: Alejandro Rios
import numpy as np 
from sklearn import preprocessing
# Datos de prueba
input_data = np.array([[5.1, -2.9, 3.3], [-1.2, 7.8, -6.1], [3.9, 0.4, 2.1], [7.3, -9.9, -4.5], [5.3, -2.9, -6.2]])
print(input_data)

[[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]
 [ 5.3 -2.9 -6.2]]


In [15]:
# Binarizar los datos
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data) 
print("\nDatos binarizados:\n", data_binarized)


Datos binarizados:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [16]:
# Imprimir la media y la desviación estándar
print("\nANTES:") 
print("Media =", input_data.mean(axis=0))
print("Desviación estándar =", input_data.std(axis=0))


ANTES:
Media = [ 4.08 -1.5  -2.28]
Desviación estándar = [2.85685141 5.73724673 4.12814728]


In [17]:
# Remover la media
data_scaled = preprocessing.scale(input_data) 
print("\nDESPUÉS:")
print("Media =", data_scaled.mean(axis=0)) 
print("Desviación estándar =",
data_scaled.std(axis=0))


DESPUÉS:
Media = [-9.99200722e-17  0.00000000e+00  0.00000000e+00]
Desviación estándar = [1. 1. 1.]


In [18]:
# Escalamiento Min Max
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max escalamiento de datos:\n", data_scaled_minmax)


Min max escalamiento de datos:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.01052632]
 [0.6        0.5819209  0.87368421]
 [1.         0.         0.17894737]
 [0.76470588 0.39548023 0.        ]]


In [19]:
# Normalización de datos
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 dato normalizado:\n", data_normalized_l1) 
print("\nL2 dato normalizado:\n", data_normalized_l2)


L1 dato normalizado:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]
 [ 0.36805556 -0.20138889 -0.43055556]]

L2 dato normalizado:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]
 [ 0.61223623 -0.33499718 -0.71620087]]


In [21]:
# Manejo de etiquetas
import numpy as np 
from sklearn import preprocessing
# Se definen algunas etiquetas simples 
input_labels = ['up', 'down', 'right', 'left', 'back', 'foward', 'ok']
# Se crea un codificador de etiquetas y se ajustan las etiquetas 
encoder = preprocessing.LabelEncoder() 
encoder.fit(input_labels)
# Se imprime el mapeo entre palabras y números print("\nMapeo de etiquetas:") 
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)
# Codificar un conjunto de etiquetas con el codificador 
test_labels = ['down', 'right', 'up'] 
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels) 
print("Encoded values =", list(encoded_values))
# Decodificar un conjunto de valores usando el codificador 
encoded_values = [3, 0, 4, 1] 
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values) 
print("Decoded labels =", list(decoded_list))


back --> 0
down --> 1
foward --> 2
left --> 3
ok --> 4
right --> 5
up --> 6

Labels = ['down', 'right', 'up']
Encoded values = [1, 5, 6]

Encoded values = [3, 0, 4, 1]
Decoded labels = ['left', 'back', 'ok', 'down']
