In [2]:
# COMPUTACIÓN BLANDA - Sistemas y Computación
# ------------------------------------------- # Introducción a
#numpy # ------------------------------------------- # Lección 01
## ** Creación de arrays # ** Acceso a los arrays # **
#Manejo de rangos # ** Modificación de arrays ##
#Editador por: Alejandro Rios - 1088035801

In [3]:
# Se importa la librería numpy
import numpy as np
# Se crea una array con 9 elementos 
a = np.arange(9)
# Se imprime en pantalla el contenido del array a
print('Arreglo a =', a, '\n')
# Se muestra el tipo de los elementos del array 
print('Tipo de a =', a.dtype, '\n')
# Se calcula la dimensión del array a, en este caso dimensión = 1 (vector) 
print('Dimensión de a =', a.ndim, '\n')
# Se calcula el número de elementos del array a 
# No olvidar que existe un elemento con índice 0 
print('Número de elementos de a =', a.shape)

Arreglo a = [0 1 2 3 4 5 6 7 8] 

Tipo de a = int32 

Dimensión de a = 1 

Número de elementos de a = (9,)


In [4]:
# Creando un arreglo multidimensional
# La matriz se crea con la función: array 
m = np.array([np.arange(3), np.arange(3)]) 
print(m)

[[0 1 2]
 [0 1 2]]


In [5]:
# Seleccionando elementos de un array 
a = np.array([[1,2,3], [4,5,6]]) 
print('a =\n', a, '\n')
# Elementos individuales 
print('a[0,0] =', a[0,0], '\n') 
print('a[0,1] =', a[0,1], '\n') 
print('a[0,2] =', a[0,2], '\n') 
print('a[1,0] =', a[1,0], '\n')
print('a[1,1] =', a[1,1], '\n')
print('a[1,2] =', a[1,2])

a =
 [[1 2 3]
 [4 5 6]] 

a[0,0] = 1 

a[0,1] = 2 

a[0,2] = 3 

a[1,0] = 4 

a[1,1] = 5 

a[1,2] = 6


In [6]:
# Crea un array con 9 elementos, desde 0 hasta 8
a = np.arange(9) 
print('a =', a, '\n')
# Muestra los elementos desde 0 hasta 9. Imprime desde 0 hasta 8 
print('a[0:9] = ', a[0:9], '\n')
# Muestra desde 3 hasta 7. Imprime desde 3 hasta 6
print('a[3,7] =', a[3:7])

a = [0 1 2 3 4 5 6 7 8] 

a[0:9] =  [0 1 2 3 4 5 6 7 8] 

a[3,7] = [3 4 5 6]


In [7]:
# Mostrando todos los elementos, desde el 1 hasta el 8, de uno en uno
print('a[1:9:1] =', a[1:9:1], '\n')
# El mismo ejemplo, pero omitiendo el número 0 al principio, el cual no es nec esario aquí
print('a[:9:1] =', a[:9:1], '\n')
# Mostrando los números, de dos en dos
print('a[0:9:2] =', a[0:9:2], '\n')
# Mostrando los números, de tres en tres
print('a[0:9:3] =', a[0:9:3])

a[1:9:1] = [1 2 3 4 5 6 7 8] 

a[:9:1] = [0 1 2 3 4 5 6 7 8] 

a[0:9:2] = [0 2 4 6 8] 

a[0:9:3] = [0 3 6]


In [8]:
# Si utilizamos un incremento negativo, el array se muestra en orden inverso
# El problema es que no muestra el valor 0
print('a[9:0:-1] =', a[9:0:-1], '\n')
# Si se omiten los valores de índice, el resultado es preciso 
print('a[::-1] =', a[::-1])

a[9:0:-1] = [8 7 6 5 4 3 2 1] 

a[::-1] = [8 7 6 5 4 3 2 1 0]


In [9]:
# Utilización de arreglos multidimensionales
b = np.arange(48).reshape(2,6,4)
print('b =\n', b)
# La instrucción reshape genera una matriz con 2 bloques, 3 filas y 4 columnas 
# El número total de elementos es de 24 (generados por arange)

b =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [10]:
# Acceso individual a los elementos del array
# Elemento en el bloque 1, fila 2, columna 3
print('b[1,2,3] =', b[1,2,3], '\n')
# Elemento en el bloque 0, fila 2, columna 2
print('b[0,2,2] =', b[0,3,2], '\n')
# Elemento en el bloque 0, fila 1, columna 1
print('b[0,1,1] =', b[0,1,2])

b[1,2,3] = 35 

b[0,2,2] = 14 

b[0,1,1] = 6


In [14]:
# Mostraremos como generalizar una selección
# Primero elegimos el componente en la fila 0, columna 0, del bloque 0 
print('b[0,0,0] =', b[0,0,0], '\n')
# A continuación, elegimos el componente en la fila 0, columna, pero del bloqu e 1 
print('b[1,0,0] =', b[1,0,0], '\n')
# Para elegir SIMULTANEAMENTE ambos elementos, lo hacemos utilizando dos puntos
print('b[:,0,0] =', b[:,0,0])

b[0,0,0] = 0 

b[1,0,0] = 24 

b[:,0,0] = [ 0 24]


In [15]:
# Si escribimos: b[0]
# Habremos elegido el primer bloque, pero habríamos omitido las filas y las co lumnas 
# En tal caso, numpy toma todas las filas y columnas del bloque 0 
print('b[0] =\n', b[0])

b[0] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [16]:
# Otra forma de representar b[1] es: b[1, :, :]
# Los dos puntos sin ningún valor, indican que se utilizarán todos los término s disponibles 
# En este caso, todas las filas y todas las columnas 
print('b[1,:,:] =\n', b[1,:,:])

b[1,:,:] =
 [[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [17]:
# Cuando se utiliza la notación de : a derecha o a izquierda, se puede reempla zar por ... 
# El ejemplo anterior se puede escribir así:
print('b[0, ...] =\n', b[0, ...])

b[0, ...] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [18]:
# Si queremos la fila 2 en el bloque 0 (sin que importen las columnas), se tiene: 
print('b[0,2] =', b[0,2])

b[0,2] = [ 8  9 10 11]


In [19]:
# El resultado de una selección puede utilizar luego para un cálculo posterior
# Se obtiene la fila 2 del bloque 0 (como en ejemplo anterior) 
# y se asigna dicha respuesta a la variable z 
z = b[0,2] 
print('z =', z, '\n')
# En este caso, la variable z toma el valor: [8 9 10 11]
# Si ahora queremos tomar de dicha respuesta los valores de 2 en 2, se tiene: 
print('z[::2] =', z[::2])

z = [ 8  9 10 11] 

z[::2] = [ 8 10]


In [20]:
# El ejercicio anterior se puede combinar en una expresión única, así:
print('b[0,2,::2] =', b[0,2,::2])
# Esta es una solución más compacta

b[0,2,::2] = [ 8 10]


In [21]:
# Imprime todas las columnas, independientemente de los bloques y filas
print(b, '\n')
print('b[:,:,1] =\n', b[:,:,1], '\n')
# Variante de notación (simplificada)
print('b[...,1] =\n', b[...,1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] 

b[:,:,1] =
 [[ 1  5  9 13 17 21]
 [25 29 33 37 41 45]] 

b[...,1] =
 [[ 1  5  9 13 17 21]
 [25 29 33 37 41 45]]


In [22]:
# Si queremos seleccionar todas las filas 2, independientemente
# de los bloques y columnas, se tiene:
print(b, '\n')
print('b[:,1] =', b[:,1])
# Puesto que no se menciona en la notación las columnas, se toman todos 
# los valores según corresponda

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] 

b[:,1] = [[ 4  5  6  7]
 [28 29 30 31]]


In [23]:
# En el siguiente ejemplo seleccionmos la columna 3 del bloque 0
print(b, '\n')
print('b[0,:,3] =', b[0,:,3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] 

b[0,:,3] = [ 3  7 11 15 19 23]


In [24]:
# Si queremos seleccionar la última columna del primer bloque, tenemos:
print('b[0,:,-1] =', b[0,:,-1])
# Podemos observar lo siguiente: entre corchetes encontramos tres valores 
# El primero, el cero, selecciona el primer bloque 
# El tercero, -1, se encarga de seleccionar la última columna 
# Los dos puntos, en la segunda posición, SELECCIONAN todos los 
#componentes de lad FILAS, que FORMARÁN PARTE de dicha COLUMNA
# Dado que los dos puntos definen todos los valores de las FILAS en 
# una columna específica, si quisieramos que DICHOS VALORES estuvieran 
# en orden inverso, ejecutaríamos la instrucción
print('b[0, ::-1, -1] =', b[0, ::-1, -1])
# La expresión ::-1 invierte todos los valores que se hubieran seleccionado
# Si en lugar de invertir la columna, quisieramos imprimir sus 
# valores de 2 en 2, tendríamos:
print('b[0, ::2, -1] =', b[0, ::2, -1])

b[0,:,-1] = [ 3  7 11 15 19 23]
b[0, ::-1, -1] = [23 19 15 11  7  3]
b[0, ::2, -1] = [ 3 11 19]


In [25]:
# El array original
print(b, '\n-----------------------\n')
# Esta instrucción invierte los bloques
print(b[::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] 
-----------------------

[[[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
# La instrucción: ravel(), de-construye el efecto de la instrucción: reshape
# Este es el array b en su estado matricial 
print('Matriz b =\n', b, '\n--------------------------\n')
# Con ravel() se genera un vector a partir de la matriz 
print('Vector b = \n', b.ravel())

Matriz b =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]] 
--------------------------

Vector b = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [27]:
# La instrucción: flatten() es similar a ravel()
# La diferencia es que flatten genera un nuevo espacio de memoria 
print('Vector b con flatten =\n', b.flatten())

Vector b con flatten =
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [28]:
# Se puede cambiar la estructura de una matriz con la instrucción: shape
# Transformamos la matriz en 6 filas x 8 columnas 
b.shape = (6,8)
print('b(6x8) =\n', b)

b(6x8) =
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]


In [29]:
# A partir de la matriz que acaba de ser generada, vamos a mostrar
# como se construye la transpuesta de la matriz
# Matriz original 
print('b =\n', b, '\n------------------------\n')
# Matri transpuesta 
print('Transpuesta de b =\n', b.transpose(), '\n------------------------\n')

b =
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]] 
------------------------

Transpuesta de b =
 [[ 0  8 16 24 32 40]
 [ 1  9 17 25 33 41]
 [ 2 10 18 26 34 42]
 [ 3 11 19 27 35 43]
 [ 4 12 20 28 36 44]
 [ 5 13 21 29 37 45]
 [ 6 14 22 30 38 46]
 [ 7 15 23 31 39 47]] 
------------------------



In [31]:
# Para concluir este primer módulo de numpy, mostraremos que la instrucción
# resize, ejecuta una labor similar a reshape 
# La diferencia está en que resize altera la estructura del array 
# En cambio reshape crea una copia del original, razón por la cual en 
# reshape se debe asignar el resultado a una nueva variable
# Se cambia la estructura del array b
b.resize([4,12])
# Al imprimir el array b, se observa que su estructura ha cambiado 
print('b =\n', b)

b =
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]]
